### ISSUE TITLE
请问uniform和discrete schedule的区别是什么？

### ISSUE THREAD

**Issue by YuChen-Liang** [zju-pi/diff-sampler#10]

**Comment by zhyzhouu** [comment]
uniform和discrete都是在t-space从[0.001, 1]均匀采样的schedule，不过它们从t-space到sigma-space（noise level）的映射有所不同，本repo里模型的时间输入统一都映射到了sigma-space中。前者的映射是从continuous-time DPMs导出的（VPSDE），后者是从discrete-time DPMs导出的（DDPM）。对于uniform schedule的实现，我们参考了[EDM的代码](https://github.com/NVlabs/edm/blob/main/generate.py)，对于discrete schedule，我们参考了Stable Diffusion中的[NoiseScheduleVP class](https://github.com/CompVis/stable-diffusion/blob/main/ldm/models/diffusion/dpm_solver/dpm_solver.py) （其中的linear对应了本repo的time_uniform）。

---

Both the 'time_uniform' and 'discrete' schedule are first uniformly sampled from t-space ranging from 0.001 to 1. But they differ from the mapping from t-space to sigma-space (i.e. noise level) and in our repo we unified the time input of pre-trained diffusion models to the sigma-space. The former one is derived from continuous-time DPMs (VPSDE) while the latter one from discrete-time DPMs (DDPM). For the 'time_uniform' schedule we refer to the [EDM repo](https://github.com/NVlabs/edm/blob/main/generate.py), and for the 'discrete' schedule we refer to the [NoiseScheduleVP class](https://github.com/CompVis/stable-diffusion/blob/main/ldm/models/diffusion/dpm_solver/dpm_solver.py) in the Stable Diffusion repo. (The 'linear' schedule in this repo corresonds to our 'time_uniform' schedule)
