### ISSUE TITLE
Reproduction code for Figure 4

### ISSUE THREAD

**Issue by vinhsuhi** [zju-pi/diff-sampler#14]
Dear authors,

Thank you for the nice paper.
Could you please publish the code to reproduce Figure 4 in the paper?

Kind regards,

**Comment by zhyzhouu** [comment]
We have released the code to reproduce Fig.4 [here](https://github.com/zju-pi/diff-sampler/blob/main/diff-analyzer-main/main.ipynb) (in the last cell). Hope it to be helpful :)
