### ISSUE TITLE
关于AMED-Solver中有关M参数的疑问

### ISSUE THREAD

**Issue by WLU-wry02** [zju-pi/diff-sampler#16]
理论上来说增大M应该会得到一个更精确的teacher sampling trajectory，但实验结果却是M=1或是2的时候最好，M=10的时候反而更差，这是为什么

**Comment by zhyzhouu** [comment]
我个人的理解是，随着M增大，teacher sampling trajectory越来越精确，学生模型的学习难度会越来越大；当M较小的时候，teacher sampling trajectory的性能有限，所以这里面存在一个trade-off。
