### ISSUE TITLE
AttributeError: 'CGPrecond' object has no attribute 'use_fp16'

### ISSUE THREAD

**Issue by Tranquil1ty** [zju-pi/diff-sampler#17]
AttributeError: 'CGPrecond' object has no attribute 'use_fp16' happen when I run the code `bash launch.sh` in the diff-solvers-main about Generating 4 images to "./samples/grids/imagenet256/dpmpp_nfe6"...

**Comment by zhyzhouu** [comment]
Fixed in the last commit by adding ``self.use_fp16 = use_fp16`` to ``class CGPrecond`` : )
