### ISSUE TITLE
Question about the function of coeff(1.15) in DP

### ISSUE THREAD

**Issue by bebebe666** [zju-pi/diff-sampler#18]
Thank you for the open-source of this awesome work. One confusing thing for me is the reason for multiplying a coeff in the dp transfer equation. Would you please tell more about the function of this coefficient and the motivation for using it?

**Comment by DefangChen** [comment]
Dynamic programming-based optimization determines the optimal time schedule that minimizes the accumulated local truncation error. This differs from the global truncation error we care about, and coeff is simply a hyper-parameter designed to mitigate the effects of this mismatch.
