### ISSUE TITLE
请问最新的GITS sampler (On the Trajectory Regularity of ODE-based Diffusion Sampling) 的相关代码何时会开源呢？

### ISSUE THREAD

**Issue by Dr-Yao-Yao** [zju-pi/diff-sampler#9]

**Comment by zhyzhouu** [comment]
感谢关注，我们最新工作[On the Trajectory Regularity of ODE-based Diffusion Sampling](https://arxiv.org/abs/2405.11326)的代码计划在七月之前开源。

---

Thanks for your attention, and we plan to open source the code of our new work [On the Trajectory Regularity of ODE-based Diffusion Sampling](https://arxiv.org/abs/2405.11326) before July.
